### ISSUE TITLE
regression tests for backend and updater

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#144]
current tests fail for unknow reason in travis and are based on randomly generated data

new tests should be based on a suitable selection randomized and anonymized real data

- [x] Create a script for anonymizing data for test database.
- [x]  Write proof-of-concept test that uses Jest and Nock to mock the API. 
- [x] Write all required regression tests. 
- [x] Write great super(bara/bot) tests!
- [x] Plug-in everything to work with the anonymized api (?)
