### ISSUE TITLE
teacher search & individual teacher statistics page

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#152]
stats to show how much credits teachers have produced (per semester, academic year)

- [x] save teachers related to credit to new table in db
- [x] add semester code to credit for teacher stats filtering
- [x] add year code and name from Oodi API to semester 
- [x] backend endpoint for querying for teachers with search term
- [x] teacher search list to frontend
- [x] endpoint for getting individual teacher data
- [x] frontend page for individual teachers

**Comment by mluukkai** [comment]
For each Unit (=koulutusohjelma) give a list of teachers for a timeframe and show number of 
- courses given
- credits produced
- number of passed/failed students
- etc
