### ISSUE TITLE
population statistics: filter presets

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#201]
eg. for lääketiede, a possibility to define and save a set of filters that would be later on easy to apply to a population

- [x] Make it possible to combine filters as a single filter

- [x] Save preset filters to database for given population

- [x] Load preset filters for populatons on query.
