### ISSUE TITLE
semester enrolments to db and population statistics filtering

### ISSUE THREAD

**Issue by ikuisma** [UniversityOfHelsinkiCS/oodikone2-frontend#214]
- [x] save semesters (code, name, etc.) to DB
- [x] save semester enrollments for students to DB 
- [x] return semester enrollments for students via population statistics endpoint
- [x] Filter students in population statistics based on enrolment status (poissa,läsnä)
