### ISSUE TITLE
Student learner profile to frontend

### ISSUE THREAD

**Issue by ikuisma** [UniversityOfHelsinkiCS/oodikone2-frontend#509]
- [x] Configure DB to ML server
- [x] Save student profiles to DB
- [x] ML endpoint for getting student profiles by search term
- [x] Request student profiles by searchterm from frontend
- [x] OodiLearn student search to frontend
- [x] OodiLearn student data page to frontend
